_biblioteca:
    path:     /Biblioteca
    defaults: { _controller: LinkFrontendBundle:Biblioteca:index }

_bibliotecaDetalle:
    path:     /bibliotecaDetalle/{biblioteca_id}
    defaults: { _controller: LinkFrontendBundle:Biblioteca:detalle, biblioteca_id: 0 }

_ajaxSearchBiblioteca:
    path:     /ajaxSearchBiblioteca
    defaults: { _controller: LinkFrontendBundle:Biblioteca:ajaxSearchBiblioteca }
    requirements:
        _method: GET

