_calendarioDeEventos:
    path:     /index/{view}/{date}
    defaults: { _controller: LinkFrontendBundle:CalendarioDeEventos:index, view: month, date: 0 }

_eventosDelUsuario:
    path:  /eventos
    defaults: { _controller: LinkFrontendBundle:CalendarioDeEventos:eventos }
