_calendarioDeEventos:
    path:     /
    defaults: { _controller: LinkFrontendBundle:CalendarioDeEventos:index }

_eventosDelUsuario:
    path:  /eventos/{userID}
    defaults: { _controller: LinkFrontendBundle:CalendarioDeEventos:eventos }
