_noticias:
    path:     /noticias
    defaults: { _controller: LinkFrontendBundle:Noticias:index }

_noticiaDetalle:
    path:     /noticiasDetalle/{noticia_id}
    defaults: { _controller: LinkFrontendBundle:Noticias:detalle, noticia_id: 0 }

_ajaxSearchNoticia:
    path:     /ajaxSearchNoticia
    defaults: { _controller: LinkFrontendBundle:Noticias:ajaxSearchNoticia }
    requirements:
        _method: GET