_usuariop:
    path:     /usuario
    defaults: { _controller: LinkFrontendBundle:Usuario:index }

_editUsuario:
    path:     /usuario
    defaults: { _controller: LinkFrontendBundle:Usuario:index }
    requirements:
        _method: POST

_ajaxClave:
    path:     /ajaxClave
    defaults: { _controller: LinkFrontendBundle:Usuario:ajaxVerificar }
    requirements:
        method: POST

_ajaxImg:
    path:     /ajaxImg
    defaults: { _controller: LinkFrontendBundle:Usuario:ajaxImagen }
    requirements:
        method: POST

_ajaxNoti:
    path:     /ajaxNoti
    defaults: { _controller: LinkFrontendBundle:Default:ajaxNoti }
    requirements:
        method: GET

_ajaxLeido:
    path:     /ajaxLeido
    defaults: { _controller: LinkFrontendBundle:Default:ajaxLeido }
    requirements:
        method: POST

_notificaciones:
    path:     /notificaciones
    defaults: { _controller: LinkFrontendBundle:Default:notificaciones }

_ajaxNotiMuro:
    path:     /ajaxNotiMuro
    defaults: { _controller: LinkFrontendBundle:Default:ajaxNotiMuro }
    requirements:
        method: GET