_usuariop:
    path:     /usuario
    defaults: { _controller: LinkFrontendBundle:Usuario:index }

_editUsuario:
    path:     /usuario
    defaults: { _controller: LinkFrontendBundle:Usuario:index }
    requirements:
        _method: POST