_usuariop:
    path:     /usuario
    defaults: { _controller: LinkFrontendBundle:Usuario:index }

_editUsuario:
    path:     /usuario
    defaults: { _controller: LinkFrontendBundle:Usuario:index }
    requirements:
        _method: POST

_ajaxClave:
    path:     /ajaxClave
    defaults: { _controller: LinkFrontendBundle:Usuario:ajaxVerificar }
    requirements:
        method: POST