parameters:
    rol:
        administrador: 1
        participante: 2
        tutor: 3
        reporte: 4
        empresa: 5
    tipo_pregunta:
        simple: 1
        multiple: 2
        asociacion: 3
    tipo_elemento:
        texto: 1
        imagen: 2
    tipo_noticias:
        noticia: 1
        novedad: 2
        biblioteca_virtual: 3
    tipo_certificado:
        empresa: 1
        pagina: 2
        grupo_paginas: 3
    tipo_imagen_certificado:
        certificado: 1
        constancia: 2
    estatus_contenido:
        borrador: 1
        activo: 2
        inactivo: 3
    tipo_destino:
        todos: 1
        nivel: 2
        programa: 3
        grupo: 4
        no_ingresado: 5
        no_ingresado_programa: 6
        aprobados: 7
    estatus_pagina:
        iniciada: 1
        en_evaluación: 2
        completada: 3
    estado_prueba:
        aprobado: 'APROBADO'
        curso: 'EN CURSO'
        reprobado: 'REPROBADO'
    social:
        muro: 1
        espacio_colaborativo: 2
    layout:
        base: 1
    folders:
        ########## CONFIGURACIÓN AMBIENTE LOCAL ##########
        uploads: 'http://localhost/uploads/'
        dir_uploads: 'C:/wamp/www/uploads/'
        dir_project: 'C:/wamp/www/formacion2.0/'
        #dir_uploads: 'C:/xampp/htdocs/uploads/'
        #dir_project: 'C:/xampp/htdocs/formacion2.0/'
        ########## CONFIGURACIÓN AMBIENTE DESARROLLO ##########
        #uploads: 'http://develop.formacion2puntocero.com/uploads/'
        #dir_project: '/home/develo/public_html/formacion2.0/'
        #dir_uploads: '/home/develo/public_html/uploads/'
    correo_recuperacion:
        asunto: 'Formación2.0 - Recuperación de usuario y clave.'
        remitente: 'tutorvirtualformacion@gmail.com'
    comandos:
        # Compilador SASS en Windows
        sass: 'C:\Ruby24-x64\bin\sass'
        # Compilador SASS en Linux
        #sass: '/usr/bin/sass'
    ponderacion:
        evaluacion: 0.5
    puntos:
        mitad_periodo: 100
        aprobar_primer_intento: 500
        aprobar_perfecto: 1000
        escribir_muro: 50
        like_recibido: 100
        respuesta_muro: 50
        espacio_colaborativo: 100
    secret: 315e95c941de6274d88f8529c9adf0a2c2b6613b
