parameters:
    rol:
        administrador: 1
        participante: 2
        tutor: 3
        reporte: 4
        empresa: 5
    tipo_pregunta:
        simple: 1
        multiple: 2
        asociacion: 3
    tipo_elemento:
        texto: 1
        imagen: 2
    folders:
        uploads: 'http://localhost/uploads/'
        dir_uploads: 'C:/wamp/www/uploads/'
        #dir_uploads: '/var/www/html/uploads/'
        #dir_uploads: 'C:/xampp/htdocs/uploads/'
    secret: 315e95c941de6274d88f8529c9adf0a2c2b6613b
