parameters:
    rol:
        administrador: 1
        participante: 2
        tutor: 3
        reporte: 4
        empresa: 5
        tutor_empresa: 8
    rol_convertir:
        rol_administrador: 'Administrador'
        rol_participante: 'Participante'
        rol_tutor: 'Tutor Virtual'
        rol_reporte: 'Reporte'
        rol_empresa: 'Empresa'
        rol_tutor_empresa: 'Tutor Empresa'
    tipo_pregunta:
        simple: 1
        multiple: 2
        asociacion: 3
    tipo_elemento:
        texto: 1
        imagen: 2
    tipo_noticias:
        noticia: 1
        novedad: 2
        biblioteca_virtual: 3
        noticia_default: 'noticia_default.png'
        novedad_default: 'novedad_default.png'
    tipo_biblioteca:
        video: 1
        podcast: 2
        articulo: 3
        libro: 4
    tipo_certificado:
        empresa: 1
        pagina: 2
        grupo_paginas: 3
    categoria:
        programa: 1
        modulo: 2
        materia: 3
        leccion: 4
        curso: 5
        competencia: 6
        recurso: 7
    tipo_imagen_certificado:
        certificado: 1
        constancia: 2
    estatus_contenido:
        borrador: 1
        activo: 2
        inactivo: 3
    tipo_destino:
        todos: 1
        nivel: 2
        programa: 3
        grupo: 4
        no_ingresado: 5
        no_ingresado_programa: 6
        aprobados: 7
        en_curso: 8
    tipo_alarma:
        respuesta_muro: 1
        espacio_colaborativo: 2
        evento: 3
        aporte_espacio_colaborativo: 4
        noticia : 5
        novedad : 6
        biblioteca : 7
        aporte_muro: 8
    tipo_correo:
        notificacion_programada: 1
        espacio_colaborativo: 2
        muro: 3
    estatus_pagina:
        iniciada: 1
        en_evaluacion: 2
        completada: 3
    estado_prueba:
        aprobado: 'APROBADO'
        curso: 'EN CURSO'
        reprobado: 'REPROBADO'
    social:
        muro: 1
        espacio_colaborativo: 2
    aplicacion:
        noticias: 17
        biblioteca: 26
    layout:
        base: 1
    notificacion_programada:
        bienvenida: 1
    correo_recuperacion:
        asunto: 'Formación Smart - Recuperación de usuario y clave.'
        remitente: 'soporte@formacionsmart.com'
    correo_soporte:
        asunto: 'Formación Smart - Solicitud de soporte virtual. '
        remitente: 'soporte@formacionsmart.com'
        destinatario: 'soporte@formacionsmart.com'
        plantilla: 'LinkFrontendBundle:Soporte:EmailSoporte.html.twig'
    ponderacion:
        evaluacion: 0.2
    puntos:
        mitad_periodo: 100
        aprobar_primer_intento: 150
        aprobar_perfecto: 100
        escribir_muro: 10
        like_recibido: 100
        respuesta_muro: 20
        espacio_colaborativo: 100
        influencer_1: 50
        influencer_2: 100
        influencer_3: 150
        amigable_1: 20
        amigable_2: 40
        amigable_3: 60
        super_smart: 400
        perfeccionista: 350
        imparable: 300
        primer_lugar: 200
        segundo_lugar: 150
        tercer_lugar: 100
        graduado: 50
        vencedor: 500
    secret: 315e95c941de6274d88f8529c9adf0a2c2b6613b
    search_locale: 0
    mailer_user: tutorvirtual@formacion2puntocero.com
    servidor_mantenimiento: 0
    fallidos:
        inbox: "{imap.formacionsmart.com:993/imap/ssl/novalidate-cert}INBOX"
        from: Mail Delivery System
        subject: Undelivered Mail Returned to Sender
        subject2: Mail Delivery Failure
        subject3: Mail delivery failed
        subject10: Warning
        separador: 'Arrival-Date:'
        separador2: '--'
        separador3: 'Diagnostic-Code: smtp;'
        separador4: 'Final-Recipient: rfc822;'
        separador5: 'Action: failed'
        separador6: --
        separadorMailMessage: '=>'
        separadorMessages: '++'
        separadorMails: '|'
        salto_linea: '%0D%0A'
    time_zone:
        default: 'UTC'
        local: 'America/Caracas'
        utc: 'UTC'
        show_time_zone: 1
        name_separator: '/'
    upload_file:
        upload_max_filesize: 80MB
    muro:
        alarma_tutor: 0
        alarma_participantes: 1
    espacio_colaborativo:
        alarma_tutor: 0
        alarma_participantes: 0
    limite_correos_notificaciones:
        cron: 50
        controlador: 0
        diario: 10000
    evaluaciones:
        puntaje_minimo: 75
        intentos: 100
    fecha_reportes:
        inicio: '1900-01-01 00:00:00'
    medallas:
        influencer_1: 1
        influencer_2: 2
        influencer_3: 3
        amigable_1: 4
        amigable_2: 5
        amigable_3: 6
        super_smart: 7
        perfeccionista: 8
        imparable: 9
        primer_lugar: 10
        segundo_lugar: 11
        tercer_lugar: 12
        graduado: 13
        vencedor: 14
    notificaciones_push:
        mostrar_maximo: 3
        maximo_minutos: 1
        minimo_segundos: 1
        maximo_segundos: 59
        

        














