parameters:
    rol:
        administrador: 1
        participante: 2
        tutor: 3
        reporte: 4
        empresa: 5
    tipo_pregunta:
        simple: 1
        multiple: 2
        asociacion: 3
    tipo_elemento:
        texto: 1
        imagen: 2
    tipo_noticias:
        noticia: 1
        novedad: 2
        biblioteca_virtual: 3
    tipo_certificado:
        empresa: 1
        pagina: 2
        grupo_paginas: 3
    tipo_imagen_certificado:
        certificado: 1
        constancia: 2 
    folders:
        uploads: 'http://localhost/uploads/'
        #dir_uploads: 'C:/wamp/www/uploads/'
        dir_uploads: '/home/develo/public_html/uploads/'
        #dir_uploads: 'C:/xampp/htdocs/uploads/'
    secret: 315e95c941de6274d88f8529c9adf0a2c2b6613b
