link_frontend:
    resource: "@LinkFrontendBundle/Resources/config/routing.yml"
    prefix:   /

link_backend:
    resource: "@LinkBackendBundle/Resources/config/routing.yml"
    prefix:   /admin

link_comun:
    resource: "@LinkComunBundle/Resources/config/routing.yml"
    prefix:   /comun