link_comun_homepage:
    path:     /
    defaults: { _controller: LinkComunBundle:Default:index }

_logout:
    path:     /logout/{ruta}
    defaults: { _controller: LinkComunBundle:Default:logout }

_logoutEmpresa:
    path:     /logoutEmpresa
    defaults: { _controller: LinkComunBundle:Default:logoutEmpresa }
