Link\ComunBundle\Entity\AdminNotificacion:
    type: entity
    table: admin_notificacion
    indexes:
        IDX_BDBBB019B394FE3:
            columns:
                - tipo_notificacion_id
        IDX_BDBBB01DB38439E:
            columns:
                - usuario_id
        IDX_BDBBB01521E1991:
            columns:
                - empresa_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        asunto:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
        mensaje:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
    manyToOne:
        tipoNotificacion:
            targetEntity: AdminTipoNotificacion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_notificacion_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: AdminUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
        empresa:
            targetEntity: AdminEmpresa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                empresa_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
