Link\ComunBundle\Entity\AdminMedallas:
    type: entity
    table: admin_medallas
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        descripcion:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
        puntos:
            type: integer
            nullable: true
            options:
                unsigned: false
        categoria:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
