Link\ComunBundle\Entity\AdminNivel:
    type: entity
    table: admin_nivel
    indexes:
        nivel_ndx1:
            columns:
                - empresa_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        fechaInicio:
            type: date
            nullable: true
            column: Fecha_inicio
        fechaFin:
            type: date
            nullable: true
            column: fecha_fin
    manyToOne:
        empresa:
            targetEntity: AdminEmpresa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                empresa_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
