Link\ComunBundle\Entity\AdminNoticia:
    type: entity
    table: admin_noticia
    indexes:
        noticia_ndx1:
            columns:
                - empresa_id
        IDX_F51CDD1FDB38439E:
            columns:
                - usuario_id
        IDX_F51CDD1F8146238:
            columns:
                - tipo_noticia_id
        IDX_F51CDD1F6AED89B7:
            columns:
                - tipo_biblioteca_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        fechaRegistro:
            type: datetime
            nullable: true
            column: fecha_registro
        resumen:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        contenido:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        fechaPublicacion:
            type: date
            nullable: true
            column: fecha_publicacion
        fechaVencimiento:
            type: date
            nullable: true
            column: fecha_vencimiento
        titulo:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
        autor:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        pdf:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        imagen:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
    manyToOne:
        empresa:
            targetEntity: AdminEmpresa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                empresa_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: AdminUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
        tipoNoticia:
            targetEntity: AdminTipoNoticia
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_noticia_id:
                    referencedColumnName: id
            orphanRemoval: false
        tipoBiblioteca:
            targetEntity: AdminTipoBiblioteca
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_biblioteca_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
