Link\ComunBundle\Entity\AdminLike:
    type: entity
    table: admin_like
    indexes:
        IDX_8C7AC253FFEB5B27:
            columns:
                - social_id
        IDX_8C7AC253DB38439E:
            columns:
                - usuario_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        entidadId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: entidad_id
    manyToOne:
        social:
            targetEntity: AdminSocial
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                social_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: AdminUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
