Link\ComunBundle\Entity\AdminLigas:
    type: entity
    table: admin_ligas
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        descripcion:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
        porcentajemin:
            type: integer
            nullable: true
            options:
                unsigned: false
        porcentajemax:
            type: integer
            nullable: true
            options:
                unsigned: false
        imagen:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
