Link\ComunBundle\Entity\AdminCronjobLog:
    type: entity
    table: admin_cronjob_log
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        mensaje:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        entidadId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: entidad_id
        fecha:
            type: date
            nullable: true
        disponible:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
