Link\ComunBundle\Entity\CertiMuro:
    type: entity
    table: certi_muro
    indexes:
        muro_ndx1:
            columns:
                - pagina_id
        IDX_F736956BDB38439E:
            columns:
                - usuario_id
        IDX_F736956B55B526F1:
            columns:
                - muro_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        mensaje:
            type: string
            nullable: true
            length: 350
            options:
                fixed: false
        fechaRegistro:
            type: datetime
            nullable: true
            column: fecha_registro
    manyToOne:
        pagina:
            targetEntity: CertiPagina
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pagina_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: AdminUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
        muro:
            targetEntity: CertiMuro
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                muro_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
