Link\ComunBundle\Entity\CertiGrupo:
    type: entity
    table: certi_grupo
    indexes:
        grupo_ndx1:
            columns:
                - empresa_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        orden:
            type: integer
            nullable: true
            options:
                unsigned: false
        imagenCertificado:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: imagen_certificado
        imagenConstancia:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: imagen_constancia
    manyToOne:
        empresa:
            targetEntity: AdminEmpresa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                empresa_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
