_bibliotecas:
    path:     /listado/{app_id}
    defaults: { _controller: LinkBackendBundle:Biblioteca:index }

_ajaxEditBiblioteca:
    path:     /ajaxEditBiblioteca
    defaults: { _controller: LinkBackendBundle:Biblioteca:ajaxEditBiblioteca }
    requirements:
        method: GET

_ajaxUpdateBiblioteca:
    path:     /ajaxUpdateBiblioteca
    defaults: { _controller: LinkBackendBundle:Biblioteca:ajaxUpdateBiblioteca }
    requirements:
        method: POST
