_empresas:
    path:     /listado/{app_id}
    defaults: { _controller: LinkBackendBundle:Empresa:index }
_registro:
    path:     /registro/{empresa_id}
    defaults: { _controller: LinkBackendBundle:Empresa:registro, empresa_id: 0 }
_ajaxActiveAplicacion:
    path:     /ajaxActiveAplicacion
    defaults: { _controller: LinkBackendBundle:Empresa:ajaxActiveAplicacion }
    requirements:
        _method: POST
