_empresas:
    path:     /listado/{app_id}
    defaults: { _controller: LinkBackendBundle:Empresa:index }
_registro:
    path:     /registro/{empresa_id}
    defaults: { _controller: LinkBackendBundle:Empresa:registro, empresa_id: 0 }
_ajaxActiveEmpresa:
    path:     /_ajaxActiveEmpresa
    defaults: { _controller: LinkBackendBundle:Empresa:_ajaxActiveEmpresa }
    requirements:
        _method: POST
