_empresasGrupo:
    path:     /empresasGrupo/{app_id}
    defaults: { _controller: LinkBackendBundle:EmpresasGrupo:index }

_ajaxGrupoPaginas:
    path:     /ajaxGrupoPaginas/
    defaults: { _controller: LinkBackendBundle:EmpresasGrupo:ajaxGrupoPaginas }

_ajaxEmpresasGrupo:
    path:     /ajaxEmpresasGrupo
    defaults: { _controller: LinkBackendBundle:EmpresasGrupo:ajaxEmpresasGrupo }
    requirements:
        method: GET

_ajaxUpdateGrupo:
    path:     /ajaxUpdateGrupo
    defaults: { _controller: LinkBackendBundle:EmpresasGrupo:ajaxUpdateGrupo }
    requirements:
        method: POST

_ajaxEditGrupo:
    path:     /ajaxEditGrupo
    defaults: { _controller: LinkBackendBundle:EmpresasGrupo:ajaxEditGrupo }
    requirements:
        method: GET

_ajaxDeleteGrupo:
    path:     /ajaxDeleteGrupo
    defaults: { _controller: LinkBackendBundle:EmpresasGrupo:ajaxDeleteGrupo }
    requirements:
        method: POST