_empresas:
    path:     /listado/{app_id}
    defaults: { _controller: LinkBackendBundle:Empresa:index }

_registro:
    path:     /registro/{empresa_id}
    defaults: { _controller: LinkBackendBundle:Empresa:registro, empresa_id: 0 }

_guardarEmpresa:
    path:     /guardarEmpresa
    defaults: {_controller: LinkBackendBundle:Empresa:guardarEmpresa }

_showEmpresa:
    path:     /mostrar/{empresa_id}
    defaults: { _controller: LinkBackendBundle:Empresa:mostrar }

_vistaPrevia:
    path:     /vistaPrevia/{empresa_id}
    defaults: { _controller: LinkFrontendBundle:Empresa:vistaPrevia }