_faqs:
    path:     /faqs/{app_id}
    defaults: { _controller: LinkBackendBundle:Faqs:index }

_ajaxUpdateFaqs:
    path:     /ajaxUpdateFaqs
    defaults: { _controller: LinkBackendBundle:Faqs:ajaxUpdateFaqs }
    requirements:
        method: POST

_ajaxRespuesta:
    path:     /ajaxRespuesta
    defaults: { _controller: LinkBackendBundle:Faqs:ajaxRespuesta }
    requirements:
        _method: GET

_ajaxEditFaqs:
    path:     /ajaxEditFaqs
    defaults: { _controller: LinkBackendBundle:Faqs:ajaxEditFaqs }
    requirements:
        _method: GET

_ajaxNuevaPregunta:
    path:     /ajaxNuevaPregunta
    defaults: { _controller: LinkBackendBundle:Faqs:ajaxNuevaPregunta }
    requirements:
        method: POST