_grupo:
    path:     /grupo/{app_id}/{empresa_id}
    defaults: { _controller: LinkBackendBundle:Grupo:index, empresa_id: 0 }

_ajaxGrupoPaginas:
    path:     /ajaxGrupoPaginas
    defaults: { _controller: LinkBackendBundle:Grupo:ajaxGrupoPaginas }
    requirements:
        method: GET

_ajaxEmpresasGrupo:
    path:     /ajaxEmpresasGrupo
    defaults: { _controller: LinkBackendBundle:Grupo:ajaxEmpresasGrupo }
    requirements:
        method: GET

_ajaxUpdateGrupo:
    path:     /ajaxUpdateGrupo
    defaults: { _controller: LinkBackendBundle:Grupo:ajaxUpdateGrupo }
    requirements:
        method: POST

_ajaxEditGrupo:
    path:     /ajaxEditGrupo
    defaults: { _controller: LinkBackendBundle:Grupo:ajaxEditGrupo }
    requirements:
        method: GET

_ajaxDeleteGrupo:
    path:     /ajaxDeleteGrupo
    defaults: { _controller: LinkBackendBundle:Grupo:ajaxDeleteGrupo }
    requirements:
        method: POST

_ajaxAsignar:
    path:     /ajaxAsignar
    defaults: { _controller: LinkBackendBundle:Grupo:ajaxAsignar }
    requirements:
        method: POST