_empresasNiveles:
    path:     /listado/{app_id}
    defaults: { _controller: LinkBackendBundle:Nivel:index }

_ajaxUpdateNivel:
    path:     /ajaxUpdateNivel
    defaults: { _controller: LinkBackendBundle:Nivel:ajaxUpdateNivel }
    requirements:
        method: POST

_ajaxTreeNiveles:
    path:     /ajaxTreeNiveles/{empresa_id}
    defaults: { _controller: LinkBackendBundle:Nivel:ajaxTreeNiveles, empresa_id: 0 }
    requirements:
        method: GET

_niveles:
    path:     /niveles/{empresa_id}
    defaults: { _controller: LinkBackendBundle:Nivel:niveles }

_ajaxUploadNivel:
    path:     /ajaxUploadNivel
    defaults: { _controller: LinkBackendBundle:Nivel:ajaxUploadNivel }
    requirements:
        method: POST

_ajaxEditNivel:
    path:     /ajaxEditNivel
    defaults: { _controller: LinkBackendBundle:Nivel:ajaxEditNivel }
    requirements:
        method: GET

_ajaxNiveles:
    path:     /ajaxNiveles
    defaults: { _controller: LinkBackendBundle:Nivel:ajaxNiveles }
    requirements:
        method: GET
