_notificacion:
    path:     /listado/{app_id}
    defaults: { _controller: LinkBackendBundle:Notificacion:index }

_ajaxNotificacion:
    path:     /ajaxNotificacion
    defaults: { _controller: LinkBackendBundle:Notificacion:ajaxNotificacion }
    requirements:
        method: GET

_ajaxUpdateNotificacion:
    path:     /ajaxUpdateNotificacion
    defaults: { _controller: LinkBackendBundle:Notificacion:ajaxUpdateNotificacion }
    requirements:
        method: POST

_ajaxEditNotificacion:
    path:     /ajaxEditNotificacion
    defaults: { _controller: LinkBackendBundle:Notificacion:ajaxEditNotificacion }
    requirements:
        method: GET

_ajaxHistoryProgramations:
    path:     /ajaxHistoryProgramtions
    defaults: { _controller: LinkBackendBundle:Notificacion:ajaxHistoryProgramations }
    requirements:
        _method: GET
