_notificacion:
    path:     /listado/{app_id}
    defaults: { _controller: LinkBackendBundle:Notificacion:index }

_ajaxNotificaciones:
    path:     /ajaxNotificaciones
    defaults: { _controller: LinkBackendBundle:Notificacion:ajaxNotificaciones }
    requirements:
        method: GET

_createNotificacion:
    path:     /createNotificacion
    defaults: { _controller: LinkBackendBundle:Notificacion:createNotificacion }

_editNotificacion:
    path:     /edit/{notificacion_id}
    defaults: { _controller: LinkBackendBundle:Notificacion:edit, notificacion_id: 0 }

_showNotificacion:
    path:     /show/{notificacion_id}/{save}
    defaults: { _controller: LinkBackendBundle:Notificacion:show, save: 0 }
