_notificacion:
    path:     /listado/{app_id}
    defaults: { _controller: LinkBackendBundle:Notificacion:index }

_ajaxNotificaciones:
    path:     /ajaxNotificaciones
    defaults: { _controller: LinkBackendBundle:Notificacion:ajaxNotificaciones }
    requirements:
        method: GET

_editNotificacion:
    path:     /edit/{notificacion_id}
    defaults: { _controller: LinkBackendBundle:Notificacion:edit, notificacion_id: 0 }

_showNotificacion:
    path:     /show/{notificacion_id}/{save}
    defaults: { _controller: LinkBackendBundle:Notificacion:show, save: 0 }

_programados:
    path:     /programados/{app_id}
    defaults: { _controller: LinkBackendBundle:Notificacion:programados }

_notificacionProgramadas:
    path:     /notificacionProgramadas/{id}
    defaults: { _controller: LinkBackendBundle:Notificacion:notificacionProgramadas }

_ajaxTreeGrupoProgramado:
    path:     /ajaxTreeGrupoProgramado/{notificacion_programada_id}
    defaults: { _controller: LinkBackendBundle:Notificacion:ajaxTreeGrupoProgramado, notificacion_programada_id: 0 }
    requirements:
        method: GET

_editNotificacionProgramada:
    path:     /editNotificacionProgramada/{notificacion_id}/{notificacion_programada_id}
    defaults: { _controller: LinkBackendBundle:Notificacion:editNotificacionProgramada, notificacion_programada_id: 0 }

_ajaxGrupoSeleccion:
    path:     /ajaxGrupoSeleccion
    defaults: { _controller: LinkBackendBundle:Notificacion:ajaxGrupoSeleccion }
    requirements:
        _method: GET

_showNotificacionProgramada:
    path:     /showNotificacionProgramada/{notificacion_programada_id}
    defaults: { _controller: LinkBackendBundle:Notificacion:showNotificacionProgramada }

_ajaxExcelCorreos:
    path:     /_ajaxExcelCorreos
    defaults: { _controller: LinkBackendBundle:Notificacion:ajaxExcelCorreos }
    requirements:
        _method: POST

_previewN:
    path:     /previewN/{id}
    defaults: { _controller: LinkBackendBundle:Notificacion:previewn }

_ajaxExcelUsuariosCorreos:
    path:     /_ajaxExcelUsuariosCorreos/
    defaults: { _controller: LinkBackendBundle:Notificacion:ajaxExcelUsuariosCorreos }
    requirements:
        _method: POST

_ajaxProgramadosEmpresa:
    path: /_ajaxProgramadosEmpresa
    defaults: { _controller: LinkBackendBundle:Notificacion:ajaxProgramadosEmpresa }
    requirements:
        _method: POST