_notificacion:
    path:     /listado/{app_id}
    defaults: { _controller: LinkBackendBundle:Notificacion:index }

_ajaxNotificaciones:
    path:     /ajaxNotificaciones
    defaults: { _controller: LinkBackendBundle:Notificacion:ajaxNotificaciones }
    requirements:
        method: GET

_createNotificacion:
    path:     /createNotificacion
    defaults: { _controller: LinkBackendBundle:Notificacion:createNotificacion }

_editNotificacion:
    path:     /editNotificacion/{notificacion_id}
    defaults: { _controller: LinkBackendBundle:Notificacion:editNotificacion, notificacion_id: 0 }

_showNotificacion:
    path:     /showNotificacion/{notificacion_id}/{status}
    defaults: { _controller: LinkBackendBundle:Notificacion:showNotificacion }