_bibliotecas:
    path:     /listado/{app_id}
    defaults: { _controller: LinkBackendBundle:Novedad:index }

_registroBiblioteca:
    path:     /registroBibliotecaVirtual/{biblioteca_id}
    defaults: { _controller: LinkBackendBundle:Novedad:registroBiblioteca, biblioteca_id: 0 }

_registroNovedad:
    path:     /registroNoticaNovedad/{noticia_id}
    defaults: { _controller: LinkBackendBundle:Novedad:registroNovedad, noticia_id: 0 }