_permisos:
    path:     /permisos/{app_id}
    defaults: { _controller: LinkBackendBundle:Permiso:index }

_permisosRol:
    path:     /permisosRol/{rol_id}
    defaults: { _controller: LinkBackendBundle:Permiso:permisosRol }
