_conexionesUsuario:
    path:     /conexionesUsuario/{app_id}
    defaults: { _controller: LinkBackendBundle:ReportesJT:conexionesUsuario }


_avanceProgramas:
    path:     /avanceProgramas/{app_id}
    defaults: { _controller: LinkBackendBundle:ReportesJT:avanceProgramas }


__ajaxConexionesUsuario: 
    path:    /ajaxConexionesUsuario/{empresa_id}
    defaults: { _controller: LinkBackendBundle:ReportesJT:ajaxConexionesUsuario }