_horasConexion:
    path:     /horasConexion/{app_id}
    defaults: { _controller: LinkBackendBundle:ReportesJE:horasConexion }

_ajaxHorasConexion:
    path:     /ajaxHorasConexion
    defaults: { _controller: LinkBackendBundle:ReportesJE:ajaxHorasConexion }
    requirements:
        _method: POST

_ajaxSaveImgHorasConexion:
    path:     /ajaxSaveImgHorasConexion
    defaults: { _controller: LinkBackendBundle:ReportesJE:ajaxSaveImgHorasConexion }
    requirements:
        _method: POST

_pdfHorasConexion:
    path:     /pdfHorasConexion/{empresa_id}/{desde}/{hasta}
    defaults: { _controller: LinkBackendBundle:ReportesJE:pdfHorasConexion, empresa_id: 0, desde: 0, hasta: 0 }

_evaluacionesModulo:
    path:     /evaluacionesModulo/{app_id}
    defaults: { _controller: LinkBackendBundle:ReportesJE:evaluacionesModulo }

_resumenRegistros:
    path:     /resumenRegistros/{app_id}
    defaults: { _controller: LinkBackendBundle:ReportesJE:resumenRegistros }
