_conexionesUsuario:
    path:     /conexionesUsuario/{app_id}
    defaults: { _controller: LinkBackendBundle:ReportesJT:conexionesUsuario }


_avanceProgramas:
    path:     /avanceProgramas/{app_id}
    defaults: { _controller: LinkBackendBundle:ReportesJT:avanceProgramas }


_ajaxConexionesUsuario: 
    path:    /ajaxConexionesUsuario
    defaults: { _controller: LinkBackendBundle:ReportesJT:ajaxConexionesUsuario }

_ajaxAvanceProgramas:
    path:   /ajaxAvanceProgramas
    defaults: { _controller:  LinkBackendBundle:ReportesJT:ajaxAvanceProgramas }

_ajaxUsuariosConectados:
    path: /ajaxUsuariosConectados
    defaults: { _controller:  LinkBackendBundle:Default:ajaxUsuariosConectados }
    requirements:
        _method: POST

_detalleParticipante:
    path: /ajaxDetalleParticipante
    defaults: { _controller: LinkBackendBundle:ReportesJT:ajaxdetalleParticipante }
    requirements: 
        _method: POST
        