_participantesEmpresa:
    path:     /participantesEmpresa/{app_id},{r}
    defaults: { _controller: LinkBackendBundle:Reportes:index, r: 1 }

_ajaxListadoParticipantes:
    path:     /ajaxListadoParticipantes
    defaults: { _controller: LinkBackendBundle:Reportes:ajaxListadoParticipantes }
    requirements:
        method: GET

_participantesRegistrados:
    path:     /participantesRegistrados/{app_id},{pagina_id},{r}
    defaults: { _controller: LinkBackendBundle:Reportes:index, pagina_id: 0,r: 2}

_participantesCursando:
    path:     /participantesCursando/{app_id},{pagina_id},{r}
    defaults: { _controller: LinkBackendBundle:Reportes:index, pagina_id: 0, r: 3 }

_ajaxProgramasE:
    path:     /ajaxProgramasE
    defaults: { _controller: LinkBackendBundle:Reportes:ajaxProgramasE }
    requirements:
        method: GET

_participantesAprobados:
    path:     /participantesAprobados/{app_id},{pagina_id},{r}
    defaults: { _controller: LinkBackendBundle:Reportes:index, pagina_id: 0 , r: 4 }

_participantesNoIniciados:
    path:     /participantesNoIniciados/{app_id},{pagina_id},{r}
    defaults: { _controller: LinkBackendBundle:Reportes:index, pagina_id: 0 , r: 5 }

_excelReporte:
    path:     /excelReporte/{app_id},{r}
    defaults: { _controller: LinkBackendBundle:Reportes:index, r:0 }
    requirements:
        method: POST