_participantesEmpresa:
    path:     /participantesEmpresa/{app_id},{r},{empresa_id}
    defaults: { _controller: LinkBackendBundle:Reportes:index, r: 1,pagina_id: 0, empresa_id: 0 }

_ajaxListadoParticipantes:
    path:     /ajaxListadoParticipantes
    defaults: { _controller: LinkBackendBundle:Reportes:ajaxListadoParticipantes }
    requirements:
        method: GET

_participantesRegistrados:
    path:     /participantesRegistrados/{app_id},{pagina_id},{r},{empresa_id}
    defaults: { _controller: LinkBackendBundle:Reportes:index, pagina_id: 0,r: 2, empresa_id: 0}

_participantesCursando:
    path:     /participantesCursando/{app_id},{pagina_id},{r},{empresa_id}
    defaults: { _controller: LinkBackendBundle:Reportes:index, pagina_id: 0, r: 3, empresa_id: 0 }

_ajaxProgramasE:
    path:     /ajaxProgramasE
    defaults: { _controller: LinkBackendBundle:Reportes:ajaxProgramasE }
    requirements:
        method: GET

_participantesAprobados:
    path:     /participantesAprobados/{app_id},{pagina_id},{r},{empresa_id}
    defaults: { _controller: LinkBackendBundle:Reportes:index, pagina_id: 0 , r: 4, empresa_id: 0 }

_participantesNoIniciados:
    path:     /participantesNoIniciados/{app_id},{pagina_id},{r},{empresa_id}
    defaults: { _controller: LinkBackendBundle:Reportes:index, pagina_id: 0 , r: 5, empresa_id: 0 }

_excelReporte:
    path:     /excelReporte/{app_id},{pagina_id},{r},{empresa_id}
    defaults: { _controller: LinkBackendBundle:Reportes:index, r:0, empresa_id: 0, pagina_id: 0}
    requirements:
        method: POST

_interaccionColaborativo:
    path:     /interaccionColaborativo/{app_id}
    defaults: { _controller: LinkBackendBundle:Reportes:interaccionColaborativo }

_interaccionMuro:
    path:     /interaccionMuro/{app_id}
    defaults: { _controller: LinkBackendBundle:Reportes:interaccionMuro }

reportesJE:
    resource: "@LinkBackendBundle/Resources/config/routing/reportesJE.yml"
    prefix: /reportesJE

reportesJT:
    resource: "@LinkBackendBundle/Resources/config/routing/reportesJT.yml"
    prefix: /reportesJT
