_roles:
    path:     /listado/{app_id}
    defaults: { _controller: LinkBackendBundle:Rol:index }

_RegistroRol:
    path:     /registro
    defaults: { _controller: LinkBackendBundle:Rol:registro }
