_tipoDestino:
    path:     /listado/{app_id}
    defaults: { _controller: LinkBackendBundle:TipoDestino:index }

_ajaxUpdateTipoDestino:
    path:     /ajaxUpdateTipoDestino
    defaults: { _controller: LinkBackendBundle:TipoDestino:ajaxUpdateTipoDestino }
    requirements:
        method: POST

_ajaxEditTipoDestino:
    path:     /ajaxEditTipoDestino
    defaults: { _controller: LinkBackendBundle:TipoDestino:ajaxEditTipoDestino }
    requirements:
        method: GET
