_tutorial:
    path:     /tutorial/{app_id}
    defaults: { _controller: LinkBackendBundle:Tutorial:index }

_ajaxUpdateTutorial:
    path:     /ajaxUpdateTutorial
    defaults: { _controller: LinkBackendBundle:Tutorial:ajaxUpdateTutorial }
    requirements:
        method: POST

_ajaxEditTutorial:
    path:     /ajaxEditTutorial
    defaults: { _controller: LinkBackendBundle:Tutorial:ajaxEditTutorial }
    requirements:
        method: GET


_ajaxRefreshTable:
    path: /_ajaxRefreshTable
    defaults: { _controller: LinkBackendBundle:Tutorial:ajaxRefreshTable}


_ajaxDeleteTutorial:
    path: /_ajaxDeleteTutorial
    defaults: { _controller: LinkBackendBundle:Tutorial:ajaxDeleteTutorial}
    


