_usuarios:
    path:     /usuarios/{app_id}
    defaults: { _controller: LinkBackendBundle:Usuario:index }

_usuario:
    path:     /usuario/{usuario_id}
    defaults: { _controller: LinkBackendBundle:Usuario:usuario, usuario_id: 0 }

_showUsuario:
    path:     /showUsuario/{usuario_id}
    defaults: { _controller: LinkBackendBundle:Usuario:showUsuario }
