_inicio:
    path:     /
    defaults: { _controller: LinkFrontendBundle:Default:index }

_login:
    path:     /login/{empresa_id}
    defaults: { _controller: LinkFrontendBundle:Login:login }

_authExceptionEmpresa:
    path:     /authExceptionEmpresa/{mensaje}
    defaults: { _controller: LinkFrontendBundle:Login:authExceptionEmpresa }

_ajaxCorreo:
    path:     /ajaxCorreo
    defaults: { _controller: LinkFrontendBundle:Login:ajaxCorreo }
    requirements:
        _method: POST

lecciones:
    resource: "@LinkFrontendBundle/Resources/config/routing/lecciones.yml"
    prefix: /lecciones

calendarioDeEventos:
    resource: "@LinkFrontendBundle/Resources/config/routing/calendarioDeEventos.yml"
    prefix: /calendarioDeEventos

programa:
    resource: "@LinkFrontendBundle/Resources/config/routing/programa.yml"
    prefix: /

tests:
    resource: "@LinkFrontendBundle/Resources/config/routing/tests.yml"
    prefix: /tests

noticias:
    resource: "@LinkFrontendBundle/Resources/config/routing/noticias.yml"
    prefix: /noticias

certificados:
    resource: "@LinkFrontendBundle/Resources/config/routing/certificados.yml"
    prefix: /certificados