_inicio:
    path:     /
    defaults: { _controller: LinkFrontendBundle:Default:index }

_login:
    path:     /login
    defaults: { _controller: LinkFrontendBundle:Default:login }

_recuperarClave:
    path:     /recuperarClave
    defaults: { _controller: LinkFrontendBundle:Default:recuperarClave }