_inicio:
    path:     /
    defaults: { _controller: LinkFrontendBundle:Default:index }

_login:
    path:     /login/{empresa_id}
    defaults: { _controller: LinkFrontendBundle:Login:login }

_authExceptionEmpresa:
    path:     /authExceptionEmpresa/{mensaje}
    defaults: { _controller: LinkFrontendBundle:Login:authExceptionEmpresa }

_recuperarClave:
    path:     /recuperarClave
    defaults: { _controller: LinkFrontendBundle:Login:recuperarClave }

lecciones:
    resource: "@LinkFrontendBundle/Resources/config/routing/lecciones.yml"
    prefix: /lecciones
