_inicioAdmin:
    path:     /index
    defaults: { _controller: LinkBackendBundle:Default:index }

roles:
    resource: "@LinkBackendBundle/Resources/config/routing/roles.yml"
    prefix: /rol

apps:
    resource: "@LinkBackendBundle/Resources/config/routing/apps.yml"
    prefix: /app

empresas:
    resource: "@LinkBackendBundle/Resources/config/routing/empresas.yml"
    prefix: /empresa

categorias:
    resource: "@LinkBackendBundle/Resources/config/routing/categorias.yml"
    prefix: /categoria

permisos:
    resource: "@LinkBackendBundle/Resources/config/routing/permisos.yml"
    prefix: /permiso
