_inicioAdmin:
    path:     /
    defaults: { _controller: LinkBackendBundle:Default:index }

_loginAdmin:
    path:     /login
    defaults: { _controller: LinkBackendBundle:Default:login }

_authException:
    path:     /authException
    defaults: { _controller: LinkBackendBundle:Default:authException }

_ajaxDelete:
    path:     /ajaxDelete
    defaults: { _controller: LinkBackendBundle:Default:ajaxDelete }
    requirements:
        method: POST

_ajaxActive:
    path:     /ajaxActive
    defaults: { _controller: LinkBackendBundle:Default:ajaxActive }
    requirements:
        _method: POST

roles:
    resource: "@LinkBackendBundle/Resources/config/routing/roles.yml"
    prefix: /rol

apps:
    resource: "@LinkBackendBundle/Resources/config/routing/apps.yml"
    prefix: /app

empresas:
    resource: "@LinkBackendBundle/Resources/config/routing/empresas.yml"
    prefix: /empresa

categorias:
    resource: "@LinkBackendBundle/Resources/config/routing/categorias.yml"
    prefix: /categoria

permisos:
    resource: "@LinkBackendBundle/Resources/config/routing/permisos.yml"
    prefix: /permiso

niveles:
    resource: "@LinkBackendBundle/Resources/config/routing/niveles.yml"
    prefix: /nivel

usuarios:
    resource: "@LinkBackendBundle/Resources/config/routing/usuarios.yml"
    prefix: /usuario

paginas:
    resource: "@LinkBackendBundle/Resources/config/routing/paginas.yml"
    prefix: /pagina

evaluaciones:
    resource: "@LinkBackendBundle/Resources/config/routing/evaluaciones.yml"
    prefix: /evaluacion

faqs:
    resource: "@LinkBackendBundle/Resources/config/routing/faqs.yml"
    prefix: /faq

tiponotificaciones:
    resource: "@LinkBackendBundle/Resources/config/routing/tiponotificaciones.yml"
    prefix: /tiponotificacion

novedades:
    resource: "@LinkBackendBundle/Resources/config/routing/novedades.yml"
    prefix: /novedades

bibliotecas:
  resource: "@LinkBackendBundle/Resources/config/routing/bibliotecas.yml"
  prefix: /biblioteca